### ISSUE TITLE
Blogs: Site 1 admin - create blog content in microsite 1

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#118]
## User story

As a site admin on a microsite
I want to publish blog posts 
So that we can share regular updates on our project

As a site admin on a microsite
I want to publish news posts 
So that we can share regular news on our project

## Notes

We currently have the localgov_news (https://github.com/localgovdrupal/localgov_news) content type, but are thinking that a single 'article' content type might be able to provide blogs posts and news posts, with some subtle configuration options for author / date / categories erc. 

Differences between News and Blogs:

 - Content type name: News vs Blogs - could rename the content type to 'article'
 - (Optionally?) display author on blog posts
 - Any other differences? 

## Assumptions 1: 

- Do it as is! Keep the news content type.
- Change labels of 'news' to 'articles'.
- No additional fields for now.
- We should restrict terms to the group (access control on terms)
- [Meta] We need to add context to nodes so that the node is group aware, as with all content types we've been discussing.
- When creating a news article, we should only be able to see the newsrooms within this microsite.

## Assumptions 2:

- Create new content type 'blog'
- Add optional fields for 'author' and 'author biog link' on the blog content type.
- Enable multiple content types in the channels
- 

## Acceptance tests

To be confirmed. 

[Ekes will investigate the current state of -play with localgov_news and we can confirm architecture]

**Comment by ekes** [comment]
So present module:-

- does use an entity reference from news article to newsroom (it's hidden if there is only one newsroom);
- does allow multiple news rooms, each will display the news articles posted into it;
- the list of news articles on a news room is a view (non-search api) of articles referencing the room;
- has functionality to feature (up to) x (default 3) items at the top of the newsroom page (uses a last in first out queue on an entity reference field if the article is added via a checkbox when posting the article, otherwise the list can be manually curated on the newsroom form)
- has a search (search api) that is of all news article content, no matter newsroom;
- has taxonomy vocabularies for the search api search, and facets configured;
- the global search facets are shown on the newsroom (so they click through to the global search from the newsroom, and aren't filtered by the newsroom).

Given the discussion about referencing profiles, that might not be users, or having different fields for showing posting information, and changing availability of these on the *form* as well as how they are displayed, does start to feel like content types are going to be more helpful here. Unless we can leave the form alone and just change the display per the newsroom it's shown in (would still need, what, changing view mode on the view based on where it's emdedded?).

With the current set up it is possible to add another content type to the newsroom, it's not automated, you have to create the content type, add the reference field, and then manually add that content type to the search api index, and the non-search api view. There's no restriction on which content types can be posted into which newsrooms. 

It sounds like the fixed categories / facets might not be what is wanted here; and not clicking through to a combined search. That requires at a minimum changing the non-search api view to a search api view which can then be restricted to the newsroom, such that the facets then only display results with content in the newsroom. I don't know if the content editor pseudo categories that directories have might not be more appropriate here than they are on directories. Altering the view might need thought about what to do with the featured posts - removing from default results - but when a facet is selected? But then do you want facet searching, text searching, search results on news / blogs / ... at all? And if so where should they appear?

**Comment by willguv** [comment]
Morning all. @msayoung are there any blogs in the reference sites that we could have a look at and compare against @ekes thoughts above? Cheers

**Comment by msayoung** [comment]
thanks for the summary @ekes 

_has a search (search api) that is of all news article content, no matter newsroom;_
_the global search facets are shown on the newsroom (so they click through to the global search from the newsroom, and aren't filtered by the newsroom)._

These two points seem very strange to me. I had to install locally to understand / check what you were saying. 

To clarify:

When you are on a newsroom we see the filters that apply to _any_ news/blog content across the site: eg: https://demo.localgovdrupal.org/news - in this example there is a filter labelled 2022. there is no content in the current Newsroom created in 2022. 

When you apply any filter you are taken to a page which lists all the articles on the site with that term, not just a filtered version of this page. Confusingly the layout also changes. https://demo.localgovdrupal.org/news/search?f%5B0%5D=date%3A2021&f%5B1%5D=date%3A2022

Anyway, I agree that we probably don't want this on microsites. Do we really want it at all? I'd love to see some research / testing on this. (maybe it already exists).

------------------------------------------

In so far as how the microsite litmus sites behave:

Most don't have any filters or news specific search:

Those that do have custom filter terms:

- http://www.lscb.org.uk/news/
- https://croydonlcsb.org.uk/category/news/

Some allow date filtering, but not from the main listing.

- https://www.haringey.gov.uk/news/archive
- https://www.tottenham.london/news-and-events/news-archive

I can't see any that use featured articles.

**Comment by finnlewis** [comment]
Reading the comments above and mulling it over further, I'm leaning heavily towards two different content types for news and blogs. 

There a number of content strategy type posts describing the fundamental differences between news and blogs which are interesting: 

https://www.spindogs.co.uk/blog/should-you-separate-the-news-and-blog-sections-of-your-website/
https://www.ocreations.com/blogs-vs-news-whats-the-difference/

Largely comes down to news being factual and blogs being opinion, but also a different tone of voice and audience. Maintaining a clean separation makes more sense to me now from a content design perspective, and probably makes it cleaner from a technical architecture too. 

This might also pave the way for a news microsite and a blogs microsite serving up different types of content to different audiences. 

So how about we bring [localgov_news](https://github.com/localgovdrupal/localgov_news/) into the microsites install with minimal changes. Then add a localgov_blog module with similar patterns and a new content type for blog posts.

**Comment by ekes** [comment]
> When you are on a newsroom we see the filters that apply to any news/blog content across the site: eg: https://demo.localgovdrupal.org/news - in this example there is a filter labelled 2022. there is no content in the current Newsroom created in 2022.

> When you apply any filter you are taken to a page which lists all the articles on the site with that term, not just a filtered version of this page. Confusingly the layout also changes. https://demo.localgovdrupal.org/news/search?f%5B0%5D=date%3A2021&f%5B1%5D=date%3A2022

Yes and further if you post more newsrooms they all have the facets for the global search, and click through to the search of all newsrooms.

**Comment by msayoung** [comment]
Putting this in to the backlog. Question of blogs is parked, and News is already in.

**Comment by finnlewis** [comment]
@willguv I'm just discussing this with @msayoung 

My memory is that this is an important feature for microsites. It is listed as a "should" in the backlog spreadsheet. 

https://docs.google.com/spreadsheets/d/1cfc3-k9FklP1PD5xHjdTrL9x9jbGmm7EjlgvLTvX2Zw/edit#gid=0&range=88:88

Shall we prioritise this for sprint 10?

**Comment by finnlewis** [comment]
Also see https://github.com/localgovdrupal/localgov_microsites/issues/195

**Comment by willguv** [comment]
Replying for the record...

We agreed in sprint planning that Groups 3/ Layout paragraphs are more important than this, but @msayoung @markconroy can start on this if time

**Comment by finnlewis** [comment]
Discussing in standup - we probably want to make this a stand alone module that can be used in Localgov core as well as microsites.

**Comment by stephen-cox** [comment]
I've created a basic Blogs module with 2 content types (blog channel and blog post): https://github.com/localgovdrupal/localgov_blogs

@msayoung We don't have a spec of the blogs fields. Was going to follow largely what news does but let's discuss.

**Comment by msayoung** [comment]
Hey @stephen-cox 

Lovely. 

My assumptions are 

- Use the same fields as News - except for the categories. I imagine we _might_ want a different set of terms here. Happy to discuss/ check with others though
- Add an author field. I assume the author will be some sort of entity. Taxonomy term / custom entity. This will at minimum be displayed on the blog article ( Maybe image, text, no link for a start?). Perhaps we can also expose the author as a filter on the blog listing page.

@finnlewis any other thoughts?

**Comment by msayoung** [comment]
I've bodged a wireframe here: https://miro.com/app/board/uXjVO9o1iRk=/?moveToWidget=3458764533869596477&cot=14

**Comment by msayoung** [comment]
Although, obviously the Layout paragraph bit won't be there for non-Microsite blogs by default

**Comment by stephen-cox** [comment]
Thanks @msayoung. Most of this makes sense to me,

- Topics are used throughout LGD so if we're categorizing blogs I think it makes sense to include this. We may also want to include a blog specific category too. Maybe this needs a discussing with more people.
- The author stuff needs more definition. We discussed having lists of people and such like, so they're entities of some type. I think we need to look at how they'll be used. For blogs a simple taxonomy would do, but if we want to re-use them then we need to look what theses cases are. I'll hold back on this for now and we can discuss next sprint

**Comment by msayoung** [comment]
Ok, I have more definition, discussed with Will. 

https://miro.com/app/board/uXjVOStMNW8=/?moveToWidget=3458764534399942518&cot=14

**Comment by msayoung** [comment]
- [x] Blog author taxonomy, we'll link to the taxonomy term page
- [x] Add a channel introduction, display in the sidebar of both channel and blog post as per GDS blog
- [x] Add recent posts to sidebar of blog (showing other blog posts in this channel)
- [ ] Add reading time to blog teaser
- [x] LInk to category taxonomy term page (need to test this, as category is used across content)
- [x] In the teasers shown on author and categories, show the related blog channel.
