### ISSUE TITLE
URL aliases

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#146]
Coming from discussion on https://github.com/localgovdrupal/localgov_microsites_group/issues/23

We want to be able to set URL aliases for content on a microsite. 

As a microsite admin 
I want to set a nice URL alias on my contact page
So that people can go to site1.localgovdrupal.org/contact 

Notes: 

This can be a problem with namespace clashes if the same path is on multiple microsites. 

Option 1: 

If we're not sharing content between microsites, we have the node s the content on the microsite and will need a cunning plan to rewrite the incoming and outgoing paths based on the group / domain. 

 - 1a: do this custom based on group
 - 1b: use domain modules

Option 2: 

Use a path alias on the group content (relationship entity). The only benefit of this is to allow one node to have multiple path aliases. 

We'll need to : 

- [x] Review the options with Domain module or related contrib to see if there's a nice option 
- [x] Decide how to do it
- [x] Do it
- [ ] Test it
- [ ] Document it

**Comment by ekes** [comment]
Using https://www.drupal.org/project/domain_path and adding some form_alter logic to restrict the options to only the entity's group domains looks promising: Would work on the entity form, not the group content entity; Would still work for shared content.

**Comment by ekes** [comment]
- [x] https://www.drupal.org/project/domain_path/issues/3281482 :facepalm:  So not pathauto being a problem it seems. 
Was confusing the hell out of me why it was disappearing.
 - [x] Fix tests
 - [x] Add test for resave
 - [x] Add test for actually using on domains
 - [x] Hiding the fields - as it also does - is throwing notices.
 - [x] Domain Pathauto testing.
 - [x] Domain Pathauto UX and Bugs -- write new issues
-  - [ ] Create three pathauto aliases for same value, they _are_ created `string`, `string-1`, `string-2` _but_ `string-1` is also replaced as the link _to_ the content for `string-1`. At least that's my manual testing of https://www.drupal.org/project/domain_path/issues/3285213 Needs automated tests and a fix
- - [ ] Pathauto checkbox is always _off_ by default, no way of changing this, you have to select it
- - [ ] We probably want to extend the automatic replacement to use group alias rather than `-1` in the first instance

**Comment by ekes** [comment]
PR https://github.com/localgovdrupal/localgov_microsites/pull/175
Follow-up https://github.com/localgovdrupal/localgov_microsites_group/issues/271

**Comment by ekes** [comment]
T'is done. Still breaky, but follow-ups have been posted and even fixed.
