### ISSUE TITLE
New content type: Fancy Directory Page

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#149]
The initial wireframes for directories had some additional fields 

- Banner image
- Standfirst
- Paragraph content (single column layout only)

![Image](https://user-images.githubusercontent.com/3852805/174999588-a3f67dd0-5924-40f8-8e3b-522136b0b08f.png)

**Comment by ekes** [comment]
Can paragraphs on directory items scare me?

If the directory is to be exposed to Open Referral, or anything else like that, unstructured nested data is a difficult, nigh on impossible, challenge.

**Comment by msayoung** [comment]
Hmm... good point. But I think the ability to have rich content for things in a directory will be very important. 
Could we _not_ expose the unstuctured date to Open Referal ? 

I was wondering whether there could be a way of turning the "Rich content" on and off on a given content type (by the microsite admin). Then the microsite admin could be made aware of the ramifications and make an informed decision.

**Comment by ekes** [comment]
> Could we not expose the unstuctured date to Open Referal ?

How do you mean? 
Dumping all referenced entities as HTML with formatting into the 'description' https://raw.githubusercontent.com/esd-org-uk/human-services/master/Resources/LGA_ApplicationProfileBasicEntityRelationshipDiagram.png but even that's challenging because it requires knowing to render all the embedded entities and presenting it as if it was a field. And assuming that putting the layout in there makes any sense?

**Comment by finnlewis** [comment]
This is now in directories, but PRs needed to bring into microsites

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/143
https://github.com/localgovdrupal/localgov_microsites_group/pull/128
