### ISSUE TITLE
Confirm architecture for front end theme

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#24]
## Notes

@ekes is thinking how we store the properties that govern the flexibility.
@markconroy and @msayoung will be thinking about how to consume these and pass to the them

Will need to be discussed.

Also need to confirm whether we'll be using block / regions etc

**Comment by markconroy** [comment]
I _think_ my preference for how to store these options would be as fields on what I am going to call the "Host" rather than theme settings. If theme settings, it might be hard to have different settings per microsite.

What I mean by "Host" is whatever entity defines the homepage - a subsite overview node, a group entity, a taxonomy term, etc - whatever we decide in the end. By doing that, we can then have access to them in views via contextual filters and relationships, and use that values from these fields to create body classes, etc that can be used in the theme.

I have a feeling the theme for this will not be making a huge amount of use of the Drupal block system (as that will require dev time/config export/etc each time you want to add something new to a page. Instead, I think a field for
- Logo
- Site name
- Footer Text Area 1
- Footer Text Area 2
- etc
will mean we can easily create variables in a preprocess or somewhere else, and use them in the theme. Everything is then "content" and not "config". Meaning if an editor changes something in the "Host", there is no dev interference needed.

**Comment by msayoung** [comment]
With Domain it is possible to override pretty much any configuration on a per site basis (I believe).

**Comment by ekes** [comment]
For me at this point (assuming groups with domain steroids), it had been as much as: should it just be fields on the group; or a custom entity that is posted into the group.

**Comment by ekes** [comment]
> With Domain it is possible to override pretty much any configuration on a per site basis (I believe).

Domain does also you to override configuration per domain. It loads custom configuration, per domain, over the main site config if it exists. This is done with domain_config. By default that is configured with domain_config_ui which does this on an admin form level; but i guess we could alternatively create our own forms on the micro site level to create these configurations.

So that is another option.

**Comment by finnlewis** [comment]
It sounds like we are arriving at a consensus on approach to microsite specific configuration based on group, domain and fields on an entity. What's the best way to document the this?
