### ISSUE TITLE
Improvement to UX of Microsite roles

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#246]
Should there be a faux checkbox to make it clear that a Member is an Editor? 
Add some help text on the Member page? 

Suggestion to document the different work flows for different users, and do some testing around names

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/191282675-a83f7af6-cd74-486c-8249-8d39fcda541f.png)



![Image](https://user-images.githubusercontent.com/3852805/191282716-ddc90c7d-c41d-4ef1-b38d-01e537a5fc49.png)



![Image](https://user-images.githubusercontent.com/3852805/191282838-11440268-75c3-4c82-a0c8-7fc641e455fb.png)



![Image](https://user-images.githubusercontent.com/3852805/191282876-296b65f0-0350-40b6-b475-a285c2663a28.png)



![Image](https://user-images.githubusercontent.com/3852805/191283370-a4cc8060-bd66-4407-90b1-cf24c62bc4f9.png)



![Image](https://user-images.githubusercontent.com/3852805/191283688-76cc68c8-f53b-45ab-a625-80179a0650bd.png)




![Image](https://user-images.githubusercontent.com/3852805/191284064-4f653d22-cd2b-4ad3-b8da-ec8ced7ed953.png)




![Image](https://user-images.githubusercontent.com/3852805/191284123-035ee8e8-ca99-4fc9-915e-63a0d40c9a4b.png)



![Image](https://user-images.githubusercontent.com/3852805/191284186-445b0974-2af3-44dd-a430-4a26d6471b5b.png)



![Image](https://user-images.githubusercontent.com/3852805/191284215-8fcc90b6-a079-4ad7-a21f-f455e6d8077c.png)



![Image](https://user-images.githubusercontent.com/3852805/191284256-270cb786-04a4-431a-b984-19cac942dbc3.png)



![Image](https://user-images.githubusercontent.com/3852805/191284324-8483ffa3-18f9-4c0e-9660-9f5e0bf09900.png)

**Comment by msayoung** [comment]
I have added some help text on the Invite member form: https://github.com/localgovdrupal/localgov_microsites_group/pull/238

**Comment by willguv** [comment]
@msayoung thanks for this

It think it needs an indication that a member has editor permissions

- a faux checkbox could work (wondering if a controller might try to uncheck the faux checkbox, but if they do they'll realise that all members are editors)

- an alternative would be to change label on the "admin" checkbox to "also make admin"

Also, is it easy to edit:

- the "Invite member/ Invite members" blue buttons? Wondering they could be labelled as "editor" rather than "member" and also why there's "invite member" and "invite members". Could one of these be dropped?

- the "Add Microsite: Group Invitation" on the first two screenshots. Should it say Add/ invite member?

**Comment by msayoung** [comment]
Lets discuss the Editor / Member question here: https://github.com/localgovdrupal/localgov_microsites_group/issues/248

**Comment by msayoung** [comment]
_the "Add Microsite: Group Invitation" on the first two screenshots. Should it say Add/ invite member?_

Add an issue here: #269
