### ISSUE TITLE
Add environment indicator module

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#372]
@Adnan-cds and Design Dave suggested that we could include the https://www.drupal.org/project/environment_indicator module. 

This could help avoid confusion between the control site and the microsite.

**Comment by Adnan-cds** [comment]
Turned out the [environment_indicator module](https://www.drupal.org/project/environment_indicator) doesn't have any hook/event to determine environments.  In the past it could do so based on fixed URLs, but that feature has been dropped too.  I ended up adding a toolbar item through a custom hook_toolbar() implementation to indicate a control site.  This toolbar item simply says "Control site: Don't edit content".  A blueish background colour is also applied to the entire toolbar.  Screenshot follows:
![screenshot-admin-toolbar-control-site-highlighting](https://github.com/localgovdrupal/localgov_microsites/assets/50206849/5e2bb3fb-fa1b-450b-ae2d-040223ada0ff)


If this is acceptable then I can raise a pull request.

**Comment by finnlewis** [comment]
Discussing briefly in Merge Monday. It would be good to see the hook you used @Adnan-cds !

@stephen-cox also mentioned that we might want to warn user 1 logged. @ekes also : "You are logged in as 'admin' on 'site 2' . " for exanple.

**Comment by Adnan-cds** [comment]
I have raised an [initial pull request](https://github.com/localgovdrupal/localgov_microsites_group/pull/407) as part of the localgov_microsites_group module.  Test runs are broken, so I am not asking anyone for a review :)

>  also mentioned that we might want to warn user 1 logged.

The admin user gets a 403 Access denied message when logged into a microsite.  So do we really need this colour toolbar feature for them?

> also : "You are logged in as 'admin' on 'site 2' . " for example.

I was thinking, if the 'admin' user is added as a member of a microsite, then they should be able to edit the site, isn't it?

Copying @finnlewis @stephen-cox @ekes
