### ISSUE TITLE
Drupal architecture - investigate Tome contrib ecosystem

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites#4]

**Comment by markconroy** [comment]
I am not sure this is an approach that will work for us. It looks like Tome is built to built a static version of your website, rather than a subset of the website. 

I did find [this interesting article](https://www.prometsource.com/blog/tome-module-how-create-static-page-dynamic-drupal-site) which kind of does what we want, but is only working on exporting one empty page (in order to get the header and footer CSS/JS/etc for use in another site).

There is also [the microsite tome module](https://www.drupal.org/project/micro_tome) but that's just an empty repository, which has been idle since 2019.

I'm [asking about the possibility](https://www.drupal.org/project/tome/issues/3273463) of this on the Tome issue queue.
